language: node_js
node_js:
- 10
- 9
- 8
env:
  MOZ_HEADLESS=1
  TEST_BROWSER=firefox
  NODE_ENV=test
addons:
  firefox: latest
branches:
  except:
  - dev-wia
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.23.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
- npm install
- npm install --only=dev
- npm install coveralls codecov
before_script: 
script:
- python ./version.py
- npm run build
- npm run nyc
- npm start
- cat ./out.log
- npm test
- npm run cov-client
- npm run e2e
- npm stop
- cat ./out.log
- ls ./uploader
- npm run cov-uploader
- npm run cov-text
- ./node_modules/.bin/nyc report --reporter=text-lcov | coveralls
- ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov && codecov
- NODE_ENV=production npm run build
after_script:

deploy:
  skip_cleanup: true
  provider: npm
  email: info@mediagoom.com
  api_key:
    secure: "UUE7KUkwSJzNNcQ7PvadQfVrRnTa7hSf7y/dEkYbwVU7cHNP4HxsqVUqasTJQV0G2GUnfpyFPXZSa8DHi7ZNW9tH9Of2RD/i7AB686oz+LktzNGjXCMOvEFPdW1iF1wr3LdgDmyOaX4sMecgSLJN4XBvcJISpUNM+O8afzBIXEPrhfu78DlNRJ4RZrmjlNk3YgP3qrYBm0jsmltd8OzRs53RzaIlvt6G77cHCGsusobEYq/WY+l1uz//9UhSgMBfO80awQlic5+EI2KPgRPuxlc+ds/UsMuD2akz6XCZsL5qlOn0BXorzJcvy3tcWR3SvBJJs45gmxv1SdopECOcuch3Z9X6wGusWytLaanLHLX711xPwrO2W4ffMuYKfWiRWA2WdKHYPd5HAPy0qsIonLuA5c9UrPEbBVdXy/RI/lO0ADjtYcVT4aAcZjWC+q5E4tqYX76SXcgBK8CLXPAUXU9eY1Gb7xtusLs7DAqvUJA9YAtXliUe/INGHh6PgwwhDmxhEUvFCR9wSaVXYiP9bz0fHVG+sJD/5OQRN0thInF5LUsxmKr8YxHTSo+Ah+9kCn8eDMZ6cW/R9QlAyPDs9Xn34LhNmBhgLDriBtZJlDGAjwApmT3Bkd7kRRioVEFVcDKSfNMH8cp/Vu9VvIkm43vXWqE7GxCd4uWZsdHf95k="
  on:
    tags: true
    repo: mediagoom/chunk-upload
    node: 8
